backend:
  name: bitbucket
  repo: ccgideas/integra
  branch: master

media_folder: static/files
public_folder: /files

collections:
  - name: info
    label: Info
    files:
      - label: "CMS Info"
        name: "cmsInfo"
        file: "src/data/cms-info.md"
        fields:
          - label: "CMS ID"
            name: "cmsMaterialID"
            widget: string
          - label: Last Modified"
            name: "lastModified"
            widget: string
      - label: "Enrollment Info"
        name: "enrollmentInfo"
        file: "src/data/enrollment-info.md"
        fields:
          - label: Lists
            name: lists
            widget: list
            required: false
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Type, name: type, widget: string, required: false }
              - label: Items
                name: items
                widget: list
                fields:
                  - label: Title
                    name: title
                    widget: string
                  - label: Type
                    name: type
                    widget: string
                  - label: URL
                    name: url
                    widget: string
                  - label: File
                    name: file
                    widget: file
                  - label: Icon
                    name: icon
                    widget: string
      - label: "Contact Info"
        name: "contactInfo"
        file: "src/data/contact-info.md"
        fields:
          - label: "Enrollment Contact Number"
            name: "enrollmentContactNumber"
            widget: string
          - label: "Abbreviated Hours"
            name: "abbreviatedHours"
            widget: string
          - label: "Enroll Now URL"
            name: "enrollNowURL"
            widget: string
          - label: Lists
            name: lists
            widget: list
            required: false
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Type, name: type, widget: string, required: false }
              - label: Items
                name: items
                widget: list
                fields:
                  - label: Title
                    name: title
                    widget: string
                  - label: Type
                    name: type
                    widget: string
                  - label: URL
                    name: url
                    widget: string
                  - label: File
                    name: file
                    widget: file
                  - label: Icon
                    name: icon
                    widget: string
  - name: pages
    label: Pages
    folder: "src/pages"
    create: false
    fields:
      - label: Title
        name: title
        widget: string
      - label: Banner Image
        name: banner
        widget: file
      - label: Magnets
        name: magnets
        required: false
        widget: list
        field: {label: Magnet, name: magnet, widget: string}
        allow_add: false
      - label: Introduction
        name: introduction
        widget: object
        required: false
        fields:
          - label: Title
            name: title
            widget: string
            required: false
          - label: Body
            name: body
            widget: string
            required: false
          - label: Action
            name: action
            widget: object
            required: false
            fields:
              - label: Text
                name: text
                widget: string
                required: false
              - label: Icon
                name: icon
                widget: string
                required: false
              - label: Url
                name: url
                widget: string
                required: false
      - label: Lists
        name: lists
        widget: list
        required: false
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Type, name: type, widget: string, required: false }
          - label: Items
            name: items
            widget: list
            fields:
              - label: Title
                name: title
                widget: string
              - label: Type
                name: type
                widget: string
                required: false
              - label: File
                name: file
                widget: file
                required: false
              - label: URL
                name: url
                widget: string
                required: false
              - label: Icon
                name: icon
                widget: string
                required: false
      - label: Body
        name: body
        required: false
        widget: markdown
      - label: Slug
        name: slug
        widget: hidden
      - label: templateKey
        name: templateKey
        widget: hidden
      - label: Subtitle
        name: subTitle
        widget: hidden
      - label: indicatorColor
        name: indicatorColor
        widget: hidden
      - label: pagePadTop
        name: pagePadTop
        widget: hidden
      - label: pagePadBot
        name: pagePadBot
        widget: hidden
      - label: pageSize
        name: pageSize
        widget: hidden
      - label: disclaimers
        name: disclaimers
        widget: hidden
      - label: iconName
        name: iconName
        widget: hidden
      - label: shouldIncludeContactInfo
        name: shouldIncludeContactInfo
        widget: hidden
      - label: shouldIncludeEnrollmentInfo
        name: shouldIncludeEnrollmentInfo
        widget: hidden
      - label: listDirection
        name: listDirection
        widget: hidden
  - name: homepage
    label: Home Page
    folder: "src/homepage"
    create: false
    fields:
      - label: Title
        name: title
        widget: string
      - label: Banner Image
        name: banner
        widget: file
      - label: Lead Message
        name: lead
        widget: string
      - label: Left Align
        name: alignLeft
        widget: hidden
      - label: Callout
        name: callout
        widget: object
        required: false
        fields:
          - label: Title
            name: title
            widget: string
          - label: Body
            name: body
            widget: string
      - label: Call to Action
        name: callToAction
        widget: object
        required: false
        fields:
          - label: Title
            name: title
            widget: string
          - label: Points
            name: points
            widget: list
            field: {label: Point, name: point, widget: string}
          - label: Action
            name: action
            widget: object
            fields:
              - label: Text
                name: text
                widget: string
              - label: Icon
                name: icon
                widget: string
              - label: Url
                name: url
                widget: string
      - label: disclaimers
        name: disclaimers
        widget: list
        field: {label: Disclaimer, name: disclaimer, widget: string}
      - label: Magnets
        name: magnets
        required: false
        widget: list
        field: {label: Magnet, name: magnet, widget: string}
        allow_add: false
      - label: Slug
        name: slug
        widget: hidden
      - label: templateKey
        name: templateKey
        widget: hidden
      - label: Subtitle
        name: subTitle
        widget: hidden
      - label: indicatorColor
        name: indicatorColor
        widget: hidden
      - label: pagePadTop
        name: pagePadTop
        widget: hidden
      - label: pagePadBot
        name: pagePadBot
        widget: hidden
      - label: pageSize
        name: pageSize
        widget: hidden
      - label: iconName
        name: iconName
        widget: hidden
      - label: shouldIncludeContactInfo
        name: shouldIncludeContactInfo
        widget: hidden
      - label: shouldIncludeEnrollmentInfo
        name: shouldIncludeEnrollmentInfo
        widget: hidden
      - label: listDirection
        name: listDirection
        widget: hidden
  - name: plans
    label: Plans
    folder: "src/our-plans"
    identifier_field: subTitle
    create: true
    fields:
      - label: Title
        name: title
        widget: string
      - label: Subtitle
        name: subTitle
        widget: string
      - label: Introduction
        name: introduction
        widget: object
        required: false
        fields:
          - label: Title
            name: title
            widget: string
            required: false
          - label: Body
            name: body
            widget: string
            required: false
          - label: Size
            name: size
            widget: hidden
            required: false
          - label: Points
            name: points
            widget: list
            required: false
            field: {label: Point, name: point, widget: string}
          - label: Action
            name: action
            widget: object
            required: false
            fields:
              - label: Text
                name: text
                widget: string
                required: false
              - label: Icon
                name: icon
                widget: string
                required: false
              - label: Url
                name: url
                widget: string
                required: false
          - label: Action Secondary
            name: actionSecondary
            widget: object
            fields:
              - label: Text
                name: text
                widget: string
              - label: Icon
                name: icon
                widget: string
              - label: Url
                name: url
                widget: string
      - label: Introduction Feature
        name: introductionFeature
        widget: object
        required: false
        fields:
          - label: Title
            name: title
            widget: string
            required: false
          - label: Body
            name: body
            widget: string
            required: false
          - label: Action
            name: action
            widget: object
            required: false
            fields:
              - label: Text
                name: text
                widget: string
                required: false
              - label: Icon
                name: icon
                widget: string
                required: false
              - label: Url
                name: url
                widget: string
                required: false
          - label: Action Secondary
            name: actionSecondary
            widget: object
            fields:
              - label: Text
                name: text
                widget: string
              - label: Icon
                name: icon
                widget: string
              - label: Url
                name: url
                widget: string
      - label: Lists
        name: lists
        widget: list
        required: false
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Type, name: type, widget: string, required: false }
          - label: Items
            name: items
            widget: list
            fields:
              - label: Title
                name: title
                widget: string
              - label: Type
                name: type
                widget: string
                required: false
              - label: File
                name: file
                widget: file
                required: false
              - label: URL
                name: url
                widget: string
                required: false
              - label: Icon
                name: icon
                widget: string
                required: false
      - label: Body
        name: body
        required: false
        widget: markdown
      - label: Slug
        name: slug
        widget: hidden
      - label: templateKey
        name: templateKey
        widget: hidden
      - label: Subtitle
        name: subTitle
        widget: hidden
      - label: indicatorColor
        name: indicatorColor
        widget: hidden
      - label: pagePadTop
        name: pagePadTop
        widget: hidden
      - label: pagePadBot
        name: pagePadBot
        widget: hidden
      - label: pageSize
        name: pageSize
        widget: hidden
      - label: disclaimers
        name: disclaimers
        widget: list
        field: {label: Disclaimer, name: disclaimer, widget: string}
      - label: iconName
        name: iconName
        widget: hidden
      - label: shouldIncludeContactInfo
        name: shouldIncludeContactInfo
        widget: hidden
      - label: shouldIncludeEnrollmentInfo
        name: shouldIncludeEnrollmentInfo
        widget: hidden
      - label: listDirection
        name: listDirection
        widget: hidden
      - label: banner
        name: banner
        widget: hidden
